### ISSUE TITLE
gh-pages show up 404

### ISSUE THREAD

**Issue by dhanvi** [osirislab/Hack-Night#3]
http://isislab.github.io/Hack-Night/ is being redirected to http://blog.isis.poly.edu/Hack-Night/ which is throwing 404 
put a cname in the repo these will help you :smile: 

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by zsck** [comment]
Alternatively change the description URL to http://blog.isis.poly.edu/hack-night/
