### ISSUE TITLE
Coursera courses listed under week 0 Reverse engineering section return 404.

### ISSUE THREAD

**Issue by HDZA** [osirislab/Hack-Night#6]
https://class.coursera.org/hwswinterface-001/class 
https://class.coursera.org/malsoftware-001/class

Both these links return 404 errors. 

https://www.coursera.org/learn/malsoftware is a valid link for the "University of London's Malicious Software and its Underground Economy: Two Sides to Every Story" course.

However "University of Washington's The Hardware/Software Interface" does not seem to have a course on the new platform that coursera uses.

**Comment by HockeyInJune** [comment]
Looks like they removed it.  Someone will replace it with this:  https://www.coursera.org/specializations/cyber-security
